// 레벨별 예문과 성분별 색상 맵

// 성분별 고정 색상 (주어=파랑, 서술어=빨강, 목적어=초록,
// 부사어=주황, 관형어=보라, 보어=청록, 기타=회색)
export const ROLE_COLORS = {
  sentence: '#334155',
  subject: '#2563eb',
  predicate: '#dc2626',
  object: '#16a34a',
  complement: '#0d9488',
  adverbial: '#ea580c',
  determiner: '#7c3aed',
  other: '#64748b',
};

// 단계별 펼치기 순서: 주어 → 서술어 → 목적어 → 나머지
export const REVEAL_ORDER = ['subject', 'predicate', 'object', 'complement', 'adverbial', 'determiner', 'other'];

// 범례에 표시할 성분 목록
export const LEGEND_ROLES = ['subject', 'predicate', 'object', 'complement', 'adverbial', 'determiner'];

// 분석 언어 × 레벨별 예문 5개씩
export const EXAMPLES = {
  ko: {
    beginner: [
      '새가 난다.',
      '꽃이 예쁘다.',
      '아기가 웃는다.',
      '물이 차갑다.',
      '해가 뜬다.',
    ],
    intermediate: [
      '나는 사과를 먹는다.',
      '동생이 학교에서 공부를 한다.',
      '친구가 나에게 선물을 주었다.',
      '우리는 공원에서 축구를 한다.',
      '고양이가 물을 마신다.',
    ],
    advanced: [
      '예쁜 꽃이 정원에 피었다.',
      '그는 훌륭한 의사가 되었다.',
      '부지런한 학생이 도서관에서 책을 읽는다.',
      '작은 새가 높은 나무에서 노래한다.',
      '우리 가족은 주말에 할머니의 집을 방문했다.',
    ],
  },
  en: {
    // ===== 초급 100: 영어의 뼈대 =====
    // 1형식(주어+동사) → 1형식+부사 → 2형식(주어+be+형용사) → 2형식(주어+be+명사)
    beginner: [
      // 주어 + 동사
      'Birds fly.',
      'The dog runs.',
      'She smiles.',
      'The sun rises.',
      'The baby sleeps.',
      'The bird sings.',
      'The cat jumps.',
      'He swims.',
      'We dance.',
      'They laugh.',
      'The stars shine.',
      'The boy runs.',
      'The girl dances.',
      'My father works.',
      'My mother cooks.',
      'The children play.',
      'The old man walks.',
      'The baby cries.',
      'The phone rings.',
      'The wind blows.',
      'The flowers grow.',
      'The leaves fall.',
      'The horse jumps.',
      'The fish swims.',
      'The teacher speaks.',
      'The students listen.',
      'The dog barks.',
      'The cat sleeps.',
      'The train stops.',
      'The rain falls.',
      // 주어 + 동사 + 부사
      'The dog runs fast.',
      'She sings well.',
      'They work hard.',
      'We walk together.',
      'He speaks slowly.',
      'The baby sleeps quietly.',
      'The sun shines brightly.',
      'The children laugh loudly.',
      'She dances beautifully.',
      'The bird flies high.',
      'He runs quickly.',
      'They study hard.',
      'The cat moves quietly.',
      'We sing together.',
      'She writes carefully.',
      'The old man walks slowly.',
      'The girl smiles brightly.',
      'They play outside.',
      'He works late.',
      'The students listen carefully.',
      // 주어 + be동사 + 형용사(보어)
      'I am happy.',
      'You are kind.',
      'He is tall.',
      'She is smart.',
      'We are ready.',
      'They are busy.',
      'The sky is blue.',
      'The soup is hot.',
      'The water is cold.',
      'The room is big.',
      'The house is old.',
      'The car is new.',
      'The book is interesting.',
      'The movie is funny.',
      'The test is easy.',
      'The question is difficult.',
      'The night is dark.',
      'The morning is bright.',
      'The coffee is sweet.',
      'The winter is cold.',
      'The summer is hot.',
      'My bag is heavy.',
      'The box is empty.',
      'The street is quiet.',
      'The market is busy.',
      'Her voice is soft.',
      'His idea is good.',
      'The answer is simple.',
      'The garden is beautiful.',
      'The moon is bright.',
      // 주어 + be동사 + 명사(보어)
      'She is a doctor.',
      'I am a student.',
      'He is a teacher.',
      'They are friends.',
      'We are a family.',
      'My father is a farmer.',
      'Her mother is a nurse.',
      'The man is a pilot.',
      'The woman is a singer.',
      'My uncle is a cook.',
      'The boy is my brother.',
      'The girl is my sister.',
      'This is my book.',
      'That is your pencil.',
      'It is a small world.',
      'The dog is my friend.',
      'The cat is a good friend.',
      'English is fun.',
      'Music is my life.',
      'Seoul is a big city.',
    ],
    // ===== 중급 100: 목적어와 꾸미는 말 =====
    // 3형식(주어+동사+목적어) → +장소/시간(전치사구) → 4형식(누구에게+무엇을) → +시간 표현
    intermediate: [
      // 주어 + 동사 + 목적어
      'I eat an apple.',
      'She reads a book.',
      'He plays the piano.',
      'We watch a movie.',
      'They sing a song.',
      'I drink water.',
      'She writes a letter.',
      'He opens the door.',
      'We clean the house.',
      'They build a bridge.',
      'I like apples.',
      'She loves music.',
      'He wants a new bike.',
      'We need more chairs.',
      'They know the answer.',
      'I draw a picture.',
      'She makes a cake.',
      'He buys new shoes.',
      'We learn Korean.',
      'They speak English.',
      'I wash the dishes.',
      'She cooks dinner.',
      'He kicks the ball.',
      'We plant trees.',
      'They paint the wall.',
      'I carry a heavy bag.',
      'She wears a red dress.',
      'He throws the ball.',
      'We catch the bus.',
      'They ride bikes.',
      'I find my keys.',
      'She sells flowers.',
      'He brings his lunch.',
      'We win the game.',
      'They grow vegetables.',
      // 주어 + 동사 (+목적어) + 전치사구
      'She reads a book at home.',
      'They play soccer in the park.',
      'I drink milk in the morning.',
      'She buys bread at the store.',
      'We learn English at school.',
      'They build a house near the river.',
      'I meet my friends after school.',
      'He washes his car on the weekend.',
      'She puts the cup on the table.',
      'We eat lunch at noon.',
      'They watch birds in the forest.',
      'I write my name on the paper.',
      'He hides the key under the box.',
      'She hangs a picture on the wall.',
      'We play games after dinner.',
      'They swim in the sea.',
      'I study math in my room.',
      'He waits for the bus.',
      'She looks at the stars.',
      'We travel to the city.',
      'They walk to school every day.',
      'I keep my toys in the box.',
      'He reads the news in the evening.',
      'She teaches music at the school.',
      'We watch the sunset by the sea.',
      'They plant flowers in the garden.',
      'I wash my face in the morning.',
      'He plays the guitar at night.',
      'She draws animals in her notebook.',
      'We buy fruit at the market.',
      'They study science in the library.',
      'I call my grandmother on Sundays.',
      'He cleans his room on Saturdays.',
      'She sings songs in the shower.',
      'We make snowmen in winter.',
      // 4형식: 주어 + 동사 + ~에게 + ~을
      'He gives me a present.',
      'She tells me a funny story.',
      'He teaches us math.',
      'My friend sends me letters.',
      'She shows him her picture.',
      'The teacher asks us questions.',
      'He buys me flowers.',
      'She gives the dog fresh water.',
      'He tells the children old stories.',
      'The teacher gives us homework.',
      'She sends her friend a card.',
      'He shows me his new bike.',
      'Grandmother tells us funny stories.',
      'She makes me a warm scarf.',
      'He brings me good news.',
      // 시간 표현·부사와 함께
      'We study English every day.',
      'He opens the window every morning.',
      'He helps his brother every evening.',
      'They clean the room together.',
      'I wash my hands before dinner.',
      'She drinks tea every afternoon.',
      'We visit the museum every month.',
      'He reads books every night.',
      'They play basketball every weekend.',
      'I brush my teeth every morning.',
      'She cleans the kitchen every day.',
      'He feeds the cat every morning.',
      'We meet our cousins every summer.',
      'They sing songs very happily.',
      'She finishes her homework quickly.',
    ],
    // ===== 고급 100: 풍성한 문장 =====
    // 형용사 수식어 + 3·4형식 + 전치사구·부사 확장 + become(보어)
    advanced: [
      'The diligent student reads a difficult book in the library.',
      'My little sister became a famous singer.',
      'The small bird sings beautifully in the tall tree.',
      'Our family visited grandmother\'s old house last weekend.',
      'A kind teacher explains the new lesson clearly.',
      'The old man tells interesting stories to the children.',
      'My best friend gave me a beautiful present yesterday.',
      'The young artist draws wonderful pictures every morning.',
      'Her older brother became a brave firefighter.',
      'The happy children play fun games after school.',
      'A clever fox found fresh food in the deep forest.',
      'The tall boy writes long letters to his old friend.',
      'My wise grandmother cooks delicious food on holidays.',
      'The busy teacher helps weak students after class.',
      'The white cat drinks warm milk in the quiet kitchen.',
      'Our new neighbor builds a small garden behind the house.',
      'The little girl draws a pretty flower on the white paper.',
      'The strong player kicks the ball very hard.',
      'The gentle nurse gives warm soup to the old patient.',
      'The smart students learn new words very quickly.',
      'The brave knight rides a white horse through the dark forest.',
      'The old farmer grows fresh vegetables in the wide field.',
      'My young cousin paints colorful pictures in the art room.',
      'The tired worker drinks cold water after the long day.',
      'The kind doctor helps sick people at the small hospital.',
      'The curious child asks many questions every day.',
      'The careful driver stops the car at the red light.',
      'My old grandfather tells wonderful stories about the past.',
      'The quick rabbit jumps over the low fence.',
      'The hungry bear catches fresh fish in the cold river.',
      'The friendly waiter brings hot food to our table.',
      'The busy mother makes sweet cookies in the warm kitchen.',
      'The little puppy follows the young boy everywhere.',
      'The wise old owl watches the quiet forest at night.',
      'The proud father shows old photos to his friends.',
      'The gentle wind moves the green leaves softly.',
      'The excited fans watch the final game together.',
      'The polite student solves the hard question correctly.',
      'The lucky fisherman catches a big fish in the deep sea.',
      'The clever monkey opens the yellow box quickly.',
      'The strict coach teaches the young players every afternoon.',
      'The cheerful singer sings sweet songs on the big stage.',
      'The quiet librarian reads thick books in the empty room.',
      'The strong horse pulls the heavy cart up the hill.',
      'The tiny ant carries a big leaf across the road.',
      'The famous writer writes a new story every year.',
      'The angry cat hides under the old sofa.',
      'The small bird finds a fat worm in the green garden.',
      'The brave girl climbs the tall mountain with her father.',
      'The old clock rings every hour.',
      'The naughty puppy digs a deep hole in the yard.',
      'The smart scientist finds a new answer to the problem.',
      'The tall waiter carries six white plates carefully.',
      'The sleepy baby holds a soft toy in her small hands.',
      'The generous king gives gold coins to the poor people.',
      'The shy student reads his poem in a low voice.',
      'The fast runner wins the long race every time.',
      'The careful nurse washes her hands before every meal.',
      'The playful kitten chases the red ball around the room.',
      'The honest boy tells the truth to his teacher.',
      'The talented chef cooks special food for important guests.',
      'The little duck swims behind its mother in the pond.',
      'The pretty butterfly flies over the yellow flowers.',
      'The strong wind opens the wooden door suddenly.',
      'The good driver stops the bus at every station.',
      'The young mother sings a soft song to her sleeping baby.',
      'The funny clown tells silly jokes to the children.',
      'The old sailor knows many secrets about the blue sea.',
      'The gentle teacher reads fairy tales to the small children.',
      'The clever girl solves the difficult puzzle in ten minutes.',
      'The heavy rain falls on the quiet town all night.',
      'The white swan swims slowly across the calm lake.',
      'The kind boy shares his lunch with the new student.',
      'The great artist paints the blue sky with bright colors.',
      'The hungry students eat warm bread with fresh butter.',
      'The lazy cat sleeps on the soft pillow all day.',
      'The proud team holds the gold cup high.',
      'The friendly dog brings the newspaper to its owner every morning.',
      'The wise judge listens to both sides carefully.',
      'The quick squirrel hides small nuts under the old tree.',
      // become: ~이 되다 (보어)
      'The young man became a great doctor.',
      'Her old friend became a famous writer.',
      'The poor boy became a rich businessman.',
      'My quiet classmate became a popular actor.',
      'The small town became a busy city.',
      'The little seed became a tall tree.',
      'The shy girl became a brave leader.',
      'His old dream became a real plan.',
      'The new student became my best friend.',
      'The kind nurse became a wise doctor.',
      // 4형식 + 수식어
      'The rich lady gives the poor children warm clothes.',
      'My kind aunt sends me sweet chocolate every winter.',
      'The old professor teaches the young students ancient history.',
      'The happy grandfather tells his grandchildren funny stories every night.',
      'The friendly baker gives me fresh bread every morning.',
      // 부사 여러 개
      'The tired traveler walks very slowly up the steep hill.',
      'The little children dance very happily at the spring festival.',
      'The great singer sings very beautifully on the world stage.',
      'The old turtle moves very slowly across the sandy beach.',
      'The young players practice very hard every afternoon.',
    ],
  },
};
